services:
  backend:
    build: ./backend
    container_name: catalog-backend
    volumes:
      - /opt/supermarket_catalog/backend_data:/app/data
    restart: always

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: catalog-frontend
    ports:
      - "8040:5173" # Check: Vite uses 5173 by default
    volumes:
      - ./frontend:/app
      - /app/node_modules # Avoid overwriting container's node_modules with local (if any)
    depends_on:
      - backend
